apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-app
  template:
    metadata:
      labels:
        app: harness-app
    spec:
      containers:
        - name: harness-app
          image: mrakbg/harnesspractice:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: harness-app-service
spec:
  selector:
    app: harness-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80         # External Port
      targetPort: 80   # Container Port
